export const styles = {
    container: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "20px",
      backgroundColor: "#f8f8f8",
      minHeight: "100vh",
    },
    header: {
      width: "100%",
      backgroundColor: "#a3dbe0",
      padding: "10px 20px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      boxShadow: "0 2px 5px rgba(0, 0, 0, 0.1)",
      marginBottom: "20px",
    },
    logo: {
      fontSize: "18px",
      fontWeight: "bold",
    },
    nav: {
      display: "flex",
      gap: "20px",
    },
    navLink: {
      textDecoration: "none",
      color: "#333",
      fontWeight: "bold",
      padding: "5px 10px",
      borderRadius: "4px",
      transition: "background-color 0.3s ease",
      cursor: "pointer",
    },
    searchIcon: {
      fontSize: "20px",
      cursor: "pointer",
    },
    actionBar: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      padding: "0 20px",
      marginBottom: "20px",
    },
    cadastrarButton: {
      padding: "10px 20px",
      backgroundColor: "#76c1d3",
      border: "none",
      borderRadius: "25px",
      color: "#fff",
      fontSize: "16px",
      cursor: "pointer",
    },
    filtrarButton: {
      padding: "10px 20px",
      backgroundColor: "#fff",
      border: "2px solid #333",
      borderRadius: "25px",
      color: "#333",
      fontSize: "16px",
      cursor: "pointer",
    },
    livrosGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "200px",
      width: "100%",
      padding: "0 20px",
    },
    livroCard: {
      backgroundColor: "#a3dbe0",
      padding: "20px",
      borderRadius: "8px",
      textAlign: "center",
      boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
    },
    livroCapa: {
      
      height: "150px",
      marginBottom: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#666",
      border: "2px solid f2f2f2",
      borderRadius: "8px",
    },
    livroInfo: {
      marginBottom: "10px",
    },
    verMaisButton: {
      padding: "10px",
      backgroundColor: "#007bff",
      border: "none",
      borderRadius: "50px",
      color: "#fff",
      cursor: "pointer",
      boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
    },
  };
  